<?php //[STAMP] 4cb2683812f99d8f1d4567e5244568a7
// phpcs:ignoreFile
namespace Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait LoggerTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

}
